int? nullallways;


List<String> Songsname = [
  'StarBoy',
  'Phle bhi main',
  'Satranga',
  'Duniya Jala Denge',
  'Alone',
  'Kesariya',
  'We Own it',
  'Challeya',
  'Zinda Banda',
  'Jawan Title Track',
  'Tu Maro Daryo',
  'AGAR TUM SAATH',
  'Nanpan No Nedlo',
  'Khoya Hain',
  'Papa Meri Jan',
  'Chandaliyo Ugyo Re',
  'shiddat',
  'Tum Se',
  'Phir Bhi Aas Lagi Hai Dil Mein',
  'O Maahi',
  'Apna Bana Le',
  'Tu Hai kaya mere liye ',
  'Dil Meri Na sune',
  'Tainu Khabar Nahi',
  'Humsafar ',
  'Thara Paisa Thari',
  'Tum jo Aaye Zindagi',
  'Hum Nahi Sudhrenge ',
];

List<String> songimage = [
  "assets/song5.png",
  'assets/phlebhimain.png',
  'assets/satranga.png',
 'assets/sariduniya.png',
  'assets/song1.png',
  'assets/song2.png',
   'assets/song3.png',
   'assets/challeya.png',
  'assets/zindabanda.png',
  'assets/jawan.png',
 'assets/tu maro.jpg',
  'assets/agar.jpg',
   'assets/nanpan.jpg',
   'assets/khoya.jpg',
  'assets/papa.jpg',
  'assets/chandaliyo.jpg',
   'assets/shiddat.jpg',
  'assets/tumse.jpg',
   'assets/phirbhi.jpg',
 'assets/omaahi.jpg',
 'assets/apna.jpg',
   'assets/mere.jpg',
  'assets/dil.jpg',
  'assets/tainu.jpg',
    'assets/hamdafar.jpg',
   'assets/thara.jpg',
  'assets/tum.jpg',
  'assets/hum.jpg',
];

List<String> musicList = [
  "assets/songs/Starboy(PagalWorld).mp3",
  'assets/songs/new1.mp3',
  'assets/songs/new2.mp3',
  'assets/songs/new3.mp3',
  'assets/songs/song1.mp3',
   'assets/songs/song2.mp3',
  'assets/songs/song3.mp3',
   'assets/songs/pick1.mp3',
   'assets/songs/pick2.mp3',
   'assets/songs/pick3.mp3',
   "assets/songs/Tu Maaro Dariyo.mp3",
  "assets/songs/tum saath.mp3",
    "assets/songs/nanpan.mp3",
   "assets/songs/khoya.mp3",
   "assets/songs/papa.mp3",
   "assets/songs/Chandaliyo.mp3",
 "assets/songs/shiddat.mp3",
 'assets/songs/tumse.jpg',
    "assets/songs//PhirBhi.mp3",
 "assets/songs/omaahi.mp3",
    "assets/songs/apna.mp3",
   'assets/songs/mere.jpg',
  "assets/songs/dil.mp3",
    "assets/songs/tainu.mp3",
    "assets/songs/Humsafar.mp3",
  "assets/songs/Thara.mp3",
    "assets/songs/Tum.mp3",
  "assets/songs/hum.mp3",
];
